#!/bin/bash
#-------------------------------------------------------------#
#-------------------------------------------------------------#
#𝗦𝗰𝗿𝗶𝗽𝘁 𝗪𝗿𝗶𝘁𝗲𝗿 : 𝗟𝗶𝗺𝗼𝗻 𝗛𝗼𝘀𝘀𝗮𝗶𝗻
#𝗖𝗿𝗲𝗱𝗶𝘁 : 𝗗𝗔𝗥𝗞_𝗧𝗘𝗔𝗠_𝗟𝗠𝗡𝘅𝟵
#𝗚𝗶𝘁𝗛𝘂𝗯 : 𝗟𝗠𝗡𝘅𝟵-𝗝𝗢𝗛𝗡𝗬
#𝗙𝗮𝗰𝗲𝗯𝗼𝗼𝗸 : 𝗟𝗝.𝗟𝗠𝗡𝘅𝟵
#𝗧𝗼𝗼𝗹 : 𝗗𝗶𝗿𝗲𝗰𝘁 𝗪𝗔 𝗦𝗠𝗦
#𝗩𝗲𝗿𝘀𝗶𝗼𝗻 : 𝟭.𝟬.𝟭𝘅
#-------------------------------------------------------------#
#-------------------------------------------------------------#
#𝗕𝗹𝗮𝗰𝗸   \e[30m
#𝗥𝗲𝗱     \e[31m
#𝗚𝗿𝗲𝗲𝗻   \e[32m
#𝗕𝗹𝘂𝗲    \e[33m
#𝗬𝗲𝗹𝗹𝗼𝘄  \e[34m
#𝗣𝗶𝗻𝗸    \e[35m
#𝗦𝗸𝘆     \e[36m
#𝗪𝗵𝗶𝘁𝗲   \e[37m
#-------------------------------------------------------------#
#-------------------------------------------------------------#

z="
";mBz='e ➤ ';Az='clea';tCz=' █░▀';oBz='de';fBz='read';KCz='➤" p';IBz='or ➤';hCz=' █▀"';wz='S"';dBz='" \e';Dz='open';ACz='essa';EBz=' LMN';dCz='p 2';VBz='LMNx';bCz='?tex';Jz='m/LJ';wCz='.0.1';nBz='" co';xBz='r Yo';DBz='AM ➤';PCz='Plea';FDz='? "';JBz=' JOH';JCz='nue ';KBz='NY"';KDz='sh L';HCz='To C';GBz='━━➤ ';uz='tsap';dz=' ██ ';QBz='36m ';mz='■"';uBz='numb';gz='████';jBz='r Co';Iz='k.co';gCz='▀ █▀';Lz='x9';vBz='er';SBz='gram';mCz=' ▄█"';QCz='se W';rBz=' Num';Nz=' ""';iCz='▄ █▄';Hz='eboo';kz='"';LBz='34m ';yBz='ur M';lCz='▄ ▄█';ZCz='$num';pz='━➤ T';OCz=' " "';GCz='ter ';PBz='OHNY';vCz='▄ v1';BBz='ARK ';VCz='p 3';ADz='un A';rz='➤ Di';HBz='Auth';WBz='9"';Rz='a\a';Xz='██  ';Yz='    ';tz=' Wha';YBz='Face';yz='  ■━';hBz='" ■━';Zz='███ ';CBz='➤ TE';Oz=' -e ';nCz=' █▀▄';Tz='5m■━';DCz='ge';Wz='6m  ';LCz='ress';CDz='x9 W';qBz='r WA';Kz='.LMN';qz='ool ';sBz='ber ';oz=' ■━━';JDz='➤ ba';cz='  ██';az='   █';aCz='ber/';sz='rect';EDz='ol ?';MCz='slee';ez='███';cCz='t=$m';iBz='Ente';nz='32m ';RCz='ait.';NDz='h"';uCz='█ ██';gBz=' -p ';iz='█  █';Vz='━■';lz='35m■';OBz='x9-J';qCz='▀ LM';oCz=' █▀█';hz='█ ██';tBz='➤ " ';XBz='33m ';fz='5m  ';fCz='█ █▀';Mz='echo';xCz='■━━━';Sz='\e[3';TCz='Load';UBz='ARK_';lBz=' Cod';Ez=' htt';MBz='GitH';YCz='code';Gz='/fac';UCz='ing.';IDz='& En';BCz='ge ➤';NCz='p 1';rCz=' █▄▀';kCz='▄ ██';sCz=' █▄█';wBz='[36m';Pz='"\e[';yCz='➤  R';NBz='ub ➤';HDz='ype ';bBz='J.LM';xz='31m ';cBz='Nx9"';eBz='[33m';bz='██ █';kBz='unty';FCz='s En';MDz='wa.s';ECz='Pres';SCz='..."';CCz=' " m';ABz='━━➤D';RBz='Tele';ZBz='book';pBz='[32m';TBz=' ➤ D';eCz='  █▀';pCz=' █▄░';Uz='━━━━';aBz=' ➤ L';XCz='me/$';DDz='A To';GDz='➤  T';WCz='/wa.';FBz='x9"';Cz='xdg-';LDz='MNx9';jz='█   ';ICz='onti';BDz='gain';Qz='36m\';vz='p SM';Bz='r';Fz='ps:/';jCz='█ █▄';
eval "$Az$Bz$z$Cz$Dz$Ez$Fz$Gz$Hz$Iz$Jz$Kz$Lz$z$Mz$Nz$z$Mz$Oz$Pz$Qz$Rz$z$Sz$Tz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Vz$z$Sz$Wz$Xz$Yz$Zz$az$bz$Xz$cz$dz$cz$cz$ez$z$Sz$fz$Xz$Yz$gz$cz$bz$Zz$cz$cz$dz$dz$cz$z$Sz$Wz$Xz$Yz$bz$Zz$bz$hz$cz$az$Xz$cz$gz$z$Sz$fz$Xz$Yz$Xz$Xz$bz$iz$hz$cz$dz$Yz$cz$z$Sz$Wz$gz$Zz$Xz$Yz$bz$jz$gz$dz$cz$cz$ez$z$Sz$Tz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Vz$z$kz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Oz$Pz$nz$oz$pz$qz$rz$sz$tz$uz$vz$wz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Oz$Pz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$z$Mz$Oz$Pz$nz$yz$GBz$HBz$IBz$JBz$KBz$z$Mz$Oz$Pz$LBz$yz$GBz$MBz$NBz$EBz$OBz$PBz$kz$z$Mz$Oz$Pz$QBz$yz$GBz$RBz$SBz$TBz$UBz$VBz$WBz$z$Mz$Oz$Pz$XBz$yz$GBz$YBz$ZBz$aBz$bBz$cBz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Oz$dBz$eBz$kz$z$fBz$gBz$hBz$GBz$iBz$jBz$kBz$lBz$mBz$nBz$oBz$z$Mz$Oz$dBz$pBz$kz$z$fBz$gBz$hBz$GBz$iBz$qBz$rBz$sBz$tBz$uBz$vBz$z$Mz$Oz$dBz$wBz$kz$z$fBz$gBz$hBz$GBz$iBz$xBz$yBz$ACz$BCz$CCz$ACz$DCz$z$Mz$Oz$dBz$eBz$kz$z$fBz$gBz$hBz$GBz$ECz$FCz$GCz$HCz$ICz$JCz$KCz$LCz$z$MCz$NCz$z$Mz$OCz$z$Az$Bz$z$Mz$Nz$z$Mz$Nz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Oz$Pz$nz$oz$pz$qz$rz$sz$tz$uz$vz$wz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Oz$Pz$xz$yz$ABz$BBz$CBz$DBz$EBz$FBz$z$Mz$Oz$Pz$nz$yz$GBz$HBz$IBz$JBz$KBz$z$Mz$Oz$Pz$LBz$yz$GBz$MBz$NBz$EBz$OBz$PBz$kz$z$Mz$Oz$Pz$QBz$yz$GBz$RBz$SBz$TBz$UBz$VBz$WBz$z$Mz$Oz$Pz$XBz$yz$GBz$YBz$ZBz$aBz$bBz$cBz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$OCz$z$Mz$Oz$Pz$QBz$yz$GBz$PCz$QCz$RCz$SCz$z$Mz$Oz$Pz$QBz$yz$GBz$TCz$UCz$SCz$z$MCz$VCz$z$Cz$Dz$Ez$Fz$WCz$XCz$YCz$ZCz$aCz$bCz$cCz$ACz$DCz$z$MCz$dCz$z$Az$Bz$z$Mz$Nz$z$Mz$Nz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Oz$Pz$QBz$eCz$fCz$fCz$fCz$gCz$gCz$gCz$hCz$z$Mz$Oz$Pz$QBz$eCz$gCz$iCz$jCz$iCz$kCz$lCz$mCz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Oz$Pz$QBz$Yz$nCz$oCz$pCz$fCz$qCz$cBz$z$Mz$Oz$Pz$QBz$Yz$rCz$sCz$tCz$uCz$vCz$wCz$kz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Nz$z$Mz$Nz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Oz$Pz$QBz$xCz$yCz$ADz$BDz$EBz$CDz$DDz$EDz$FDz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Oz$Pz$QBz$xCz$GDz$HDz$IDz$GCz$JDz$KDz$LDz$MDz$NDz$z$Mz$Oz$Pz$lz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$Uz$mz$z$Mz$Nz"
